"""equipment and inspection refactor

Revision ID: 60c974bfdcc0
Revises: fefbc3d90f40
Create Date: 2026-06-03 10:54:26.492497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c974bfdcc0'
down_revision: Union[str, None] = 'fefbc3d90f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_check_items',
    sa.Column('equipment_type', sa.String(length=32), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('input_type', sa.String(length=16), nullable=False),
    sa.Column('standard_value', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('required', sa.SmallInteger(), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_check_items', schema=None) as batch_op:
        batch_op.create_index('ix_check_items_type_order', ['equipment_type', 'sort_order'], unique=False)
        batch_op.create_index('uq_check_items_type_code', ['equipment_type', 'item_code'], unique=True)

    op.create_table('equipment',
    sa.Column('equipment_code', sa.String(length=50), nullable=False),
    sa.Column('equipment_name', sa.String(length=100), nullable=False),
    sa.Column('equipment_type', sa.String(length=32), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_code')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index('ix_equipment_room_status', ['room_id', 'status'], unique=False)
        batch_op.create_index('ix_equipment_type', ['equipment_type'], unique=False)

    op.create_table('inspection_equipment_results',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['inspection_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_equipment_results', schema=None) as batch_op:
        batch_op.create_index('ix_eq_results_record', ['record_id'], unique=False)
        batch_op.create_index('uq_eq_results_record_equipment', ['record_id', 'equipment_id'], unique=True)

    op.create_table('inspection_item_results',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('check_item_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('is_abnormal', sa.SmallInteger(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['check_item_id'], ['inspection_check_items.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['inspection_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_item_results', schema=None) as batch_op:
        batch_op.create_index('ix_item_results_record_equipment', ['record_id', 'equipment_id'], unique=False)
        batch_op.create_index('uq_item_results_unique', ['record_id', 'equipment_id', 'check_item_id'], unique=True)

    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('remark',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('inspection_type')
        batch_op.drop_column('issue_level')
        batch_op.drop_column('issue_description')
        batch_op.drop_column('suggested_action')
        batch_op.drop_column('inspection_items')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inspection_items', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('suggested_action', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('issue_description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('issue_level', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('inspection_type', sa.VARCHAR(length=20), nullable=False))
        batch_op.alter_column('remark',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('source')

    with op.batch_alter_table('inspection_item_results', schema=None) as batch_op:
        batch_op.drop_index('uq_item_results_unique')
        batch_op.drop_index('ix_item_results_record_equipment')

    op.drop_table('inspection_item_results')
    with op.batch_alter_table('inspection_equipment_results', schema=None) as batch_op:
        batch_op.drop_index('uq_eq_results_record_equipment')
        batch_op.drop_index('ix_eq_results_record')

    op.drop_table('inspection_equipment_results')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index('ix_equipment_type')
        batch_op.drop_index('ix_equipment_room_status')

    op.drop_table('equipment')
    with op.batch_alter_table('inspection_check_items', schema=None) as batch_op:
        batch_op.drop_index('uq_check_items_type_code')
        batch_op.drop_index('ix_check_items_type_order')

    op.drop_table('inspection_check_items')
    # ### end Alembic commands ###
