"""initial schema

Revision ID: fefbc3d90f40
Revises: 
Create Date: 2026-06-03 10:00:42.922618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fefbc3d90f40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_logs',
    # BigInteger on real DBs, Integer on SQLite (so the column becomes a rowid alias
    # and autoincrements without explicit values in dev).
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.create_index('ix_oplog_action', ['action'], unique=False)
        batch_op.create_index('ix_oplog_user_time', ['user_id', 'created_at'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_role_status', ['role', 'status'], unique=False)

    op.create_table('attachments',
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('ix_attach_category', ['category'], unique=False)
        batch_op.create_index('ix_attach_target', ['target_type', 'target_id'], unique=False)

    op.create_table('rooms',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index('ix_rooms_status', ['status'], unique=False)

    op.create_table('inspection_records',
    sa.Column('record_no', sa.String(length=32), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('inspection_time', sa.DateTime(), nullable=False),
    sa.Column('inspection_type', sa.String(length=20), nullable=False),
    sa.Column('inspection_items', sa.Text(), nullable=False),
    sa.Column('has_issue', sa.SmallInteger(), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('issue_level', sa.String(length=20), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_no')
    )
    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.create_index('ix_records_has_issue', ['has_issue'], unique=False)
        batch_op.create_index('ix_records_inspector', ['inspector_id'], unique=False)
        batch_op.create_index('ix_records_room_status', ['room_id', 'status'], unique=False)
        batch_op.create_index('ix_records_status', ['status'], unique=False)
        batch_op.create_index('ix_records_time', ['inspection_time'], unique=False)

    op.create_table('issue_processes',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('expected_finish_time', sa.DateTime(), nullable=True),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['inspection_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_processes', schema=None) as batch_op:
        batch_op.create_index('ix_proc_assignee_action', ['assignee_id', 'action'], unique=False)
        batch_op.create_index('ix_proc_operator', ['operator_id'], unique=False)
        batch_op.create_index('ix_proc_record_time', ['record_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_processes', schema=None) as batch_op:
        batch_op.drop_index('ix_proc_record_time')
        batch_op.drop_index('ix_proc_operator')
        batch_op.drop_index('ix_proc_assignee_action')

    op.drop_table('issue_processes')
    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.drop_index('ix_records_time')
        batch_op.drop_index('ix_records_status')
        batch_op.drop_index('ix_records_room_status')
        batch_op.drop_index('ix_records_inspector')
        batch_op.drop_index('ix_records_has_issue')

    op.drop_table('inspection_records')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index('ix_rooms_status')

    op.drop_table('rooms')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index('ix_attach_target')
        batch_op.drop_index('ix_attach_category')

    op.drop_table('attachments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role_status')

    op.drop_table('users')
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_oplog_user_time')
        batch_op.drop_index('ix_oplog_action')

    op.drop_table('operation_logs')
    # ### end Alembic commands ###
